# Generated by Django 4.2.7 on 2023-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=400)),
                ('participants', models.CharField(max_length=250)),
                ('student_role', models.CharField(max_length=150)),
                ('student_goal', models.CharField(max_length=150)),
                ('lang', models.CharField(choices=[('ru-RU', 'Russian'), ('en-US', 'English')], max_length=150)),
            ],
        ),
    ]
