# Generated by Django 4.2.7 on 2024-06-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicing', '0002_situation_questions_alter_situation_lang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Situation',
            new_name='PracticingSituation',
        ),
    ]
