# Generated by Django 4.2.7 on 2024-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sentences",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("sentence", models.TextField(default="")),
                ("en_translation", models.TextField(default="")),
                ("lang", models.CharField(default="", max_length=6)),
                ("phonetic", models.TextField(default="")),
                ("ipa", models.TextField(default="")),
            ],
        ),
    ]
