# Generated by Django 4.2.7 on 2024-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickpractice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("word", models.TextField(default="")),
                ("en_translation", models.TextField(default="")),
                ("lang", models.CharField(default="", max_length=6)),
                ("phonetic", models.TextField(default="")),
                ("ipa", models.TextField(default="")),
                ("category", models.TextField(default="")),
            ],
        ),
        migrations.AddField(
            model_name="sentences",
            name="category",
            field=models.TextField(default=""),
        ),
    ]
