# Generated by Django 4.2.7 on 2024-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickpractice", "0002_words_sentences_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentences",
            name="sentence",
            field=models.TextField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="words",
            name="word",
            field=models.TextField(default="", unique=True),
        ),
    ]
