# Generated by Django 4.2.7 on 2024-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickpractice", "0004_sentences_difficulty_words_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentences",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("C2", "C2"),
                    ("A1", "A1"),
                    ("C1", "C1"),
                    ("B2", "B2"),
                    ("B1", "B1"),
                    ("A2", "A2"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="words",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("C2", "C2"),
                    ("A1", "A1"),
                    ("C1", "C1"),
                    ("B2", "B2"),
                    ("B1", "B1"),
                    ("A2", "A2"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
