# Generated by Django 4.2.7 on 2024-09-20 09:01

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleWordsVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_type', models.CharField(max_length=250, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleWordsSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/images/singlewords/'), upload_to='')),
                ('sound_type', models.ForeignKey(db_column='sound_type', on_delete=django.db.models.deletion.CASCADE, to='single_words.singlewordsvideos')),
            ],
        ),
    ]
