# Generated by Django 4.2.7 on 2024-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SingleWordsSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=250)),
                ("image", models.CharField(max_length=250)),
                ("sound_type", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="SingleWordsVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sound_type", models.CharField(max_length=250)),
                ("url", models.CharField(max_length=250)),
            ],
        ),
    ]
