# Generated by Django 4.2.7 on 2024-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlewordssituation',
            name='syllables',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
