# Generated by Django 4.2.7 on 2024-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='lang',
            field=models.CharField(choices=[('en-US', 'English'), ('ru-RU', 'Russian')], max_length=150),
        ),
    ]
